### ISSUE TITLE
Can't get a message from the Push socket

### ISSUE THREAD

**Issue by beauxjim** [BonneVoyager/MetaTrader4-Bridge#5]
I have attempted to use /zeromq/clrzmq4 and /zeromq/netmq packages in a C# console application. Both packages can send requests, and MT4 receives the requests and confirms that it is responding, but I never receive a push message in the subscription channel. 

Your node library works in a node js application.  What do you have to do to get the pull subscription working?

I appreciate your response.

Here is some code using your node plugin.. the req gets the correct response, but the pull gets just the id, which is what I'm getting in the c# zeromq packages,

```
const zmqBridge = mt4zmqBridge.connect('tcp://127.0.0.1:5555', 'tcp://127.0.0.1:5556');

setTimeout(() =>{
    console.log("Pull connected", zmqBridge.pullConnected);
},1000)


zmqBridge.onPullMessage = function(res, res2)  {
    console.log("pull", res);    

};

setTimeout(() =>{    
    zmqBridge.request(mt4zmqBridge.REQUEST_PING, '', (err, res) => {
        console.log("req", res);             
    });
},2000)
```

**Comment by BonneVoyager** [comment]
@beauxjim if you already can see the id of the request in the C# zeromq package, then you're probably missing the parsing part https://github.com/BonneVoyager/node-mt4-zmq-bridge/blob/master/index.js#L202-L218 which is required by MetaTrader4-Bridge here https://github.com/BonneVoyager/MetaTrader4-Bridge/blob/master/MetaTrader4Bridge.mq4#L188. If the parsed message doesn't recognize supported type, it might not respond due to this piece of code https://github.com/BonneVoyager/MetaTrader4-Bridge/blob/master/MetaTrader4Bridge.mq4#L500-L631.

**Comment by beauxjim** [comment]
Thank you for the response.

I will research everything mentioned.

Please note that the MT4 Expert logs show that the message was recognized and that it is responding back with a string such as "2|0|xxxx". In the response of the C# request, I only see "2". In the subscribed pull channel for C#, I see nothing. Your node library is the only thing that has successfully subscribed to the pull channel, however, it also only sees a "2" in the push messages, and that does not matter whether the original request came from the node application or the C# application.

The code above is a working example of my explanation.

Thanks again!

**Comment by BonneVoyager** [comment]
@beauxjim that `0` makes me think that your request doesn't have any type, for example `1` for PING as described in below section:
https://github.com/BonneVoyager/MetaTrader4-Bridge#request

The simplest test scenario would be to send a message with incremented id and type REQUEST_PING, so for example `123|1` (request with id 1 and type of REQUEST_PING). In the response, you should see `123|0|<timestamp>` (because of [this](https://github.com/BonneVoyager/MetaTrader4-Bridge/blob/master/MetaTrader4Bridge.mq4#L513)), where `123` is an id of your request, `0` is [RESPONSE_OK](https://github.com/BonneVoyager/MetaTrader4-Bridge/blob/master/MetaTrader4Bridge.mq4#L53) and `<timestamp>` is unix epoch.

**Comment by beauxjim** [comment]
Thank you again for your response.  After thoroughly reviewing the code and stepping through the referenced spots, I can say that the code does understand the request.  Also the bridge does say that it is responding with the ping time stamp, however the zmq push message is never received, and the req message only has the id of the message in the response.  I've attached a screen shot as a picture is worth a thousand words.

Also here is my pull client code from c#.  Is there something blatantly missing?

```
          using (var subSocket = new SubscriberSocket())
          {
              subSocket.Options.ReceiveHighWatermark = 10;
              subSocket.Connect("tcp://127.0.0.1:5556");
              subSocket.Subscribe("pull");
              Console.WriteLine("Subscriber socket connecting...");
              while (true)
              {
                  string messageTopicReceived = subSocket.ReceiveFrameString();
                  string messageReceived = subSocket.ReceiveFrameString();
                  Console.WriteLine(messageReceived);                                   
              }
          }
 
```
![Screenshot 2023-02-01 174626](https://user-images.githubusercontent.com/124094968/216339083-a8f069d0-7adf-49ac-b391-cf30e4f7a312.png)

**Comment by beauxjim** [comment]
I figured it out.  It was my lack of understanding Zmq.  I was trying to to use a Subscrition socket when I should have been using a Pull socket.  I can now see the ping response in the c# code with the timestamp.

Thanks again

**Comment by BonneVoyager** [comment]
I'm glad it worked for you @beauxjim

Did you also figure out the C# code for handling the messages? I could potentially add it to this section here https://github.com/BonneVoyager/MetaTrader4-Bridge#libraries if it's made in a reusable way?

**Comment by beauxjim** [comment]
Once I have something worth sharing, I'll send it to you!
